# -- General Configuration for AI Core Utilities --


# -- LLM General --
llm_general:
  openai:
    default_model: "gpt-4o-mini"
    models: 
      - "gpt-4o-mini"
    max_tokens: 1000
    temperature: 0.7
    top_p: 1.0
    frequency_penalty: 0.0  
    presence_penalty: 0.0
  anthropic:
    default_model: "claude-3-haiku"
    models: 
      - "claude-3-haiku"
      - "claude-3-opus"
      - "claude-2"
    max_tokens: 1000
    temperature: 0.7
    top_p: 1.0
    top_k: 250
  mistral:
    default_model: "mistral-large"
    max_tokens: 1000
    temperature: 0.7
    top_p: 0.9