[project]
name = "python-ai-core"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "anthropic>=0.52.2",
    "google>=3.0.0",
    "groq>=0.26.0",
    "mistralai>=1.8.1",
    "openai>=1.82.1",
]
